---
title: "MAT 124 - MRSA Project"
author: "Ryan Campbell, Riley Adams, Aditya Kurkut"
date: "5/14/2022"
output:
html_document: default
---
```{r setup, include=FALSE}
library("tidyr")
## General Notes
  # Installed Library BiocManager (> install.packages("BiocManager")
  # Installed package msa (> BiocManager::install("msa"))
  # View documentation (> browseVignettes("msa")). Click on pdf, source, or R code.


## Other packages we may want to consider:
  # For sequences: ClustalW, Clustal omega (recommended) and MUSCLE within R.
  # For phylogenetic trees: MEGA (external resource) or Phylogram within R.
  # For reticular evolution: TDA (topological data analysis) within R. Dr. Arsuaga mentions RDP4 (Not sure what language/software)
  # For BLAST: https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&BLAST_SPEC=&LINK_LOC=blasttab&LAST_PAGE=blastp

```

```{r}
# read in the data
library(readr)
pnas_1702472114_sd04 <- read_delim("pnas.1702472114.sd04.txt", 
    delim = ">", escape_double = FALSE, trim_ws = TRUE)
View(pnas_1702472114_sd04)

#~~~~ clean the data ~~~~~~~~~

# create/names for dataframe mrsa
mrsa <- data.frame(cbind(pnas_1702472114_sd04[2],pnas_1702472114_sd04[1]))
mrsa[1,1] <- "USA_2001_2"
colnames(mrsa) <- c("strain","sequences")

#align sequences with their strains
for (i in 2:length(mrsa$sequences)) {
  if (i %% 2 == 0){
    mrsa$sequences[i] <- mrsa$sequences[i+1]
  }
}

# remove extra copies of sequences corresponding to NA strains
# (need to remove odd rows from data frame after row 2)
```